events {}
http {
    upstream backend {
        server ml-service-blue:5000;
    }

    server {
        listen 80;

        location /health {
            proxy_pass http://backend/health;
        }

        location /predict {
            proxy_pass http://backend/predict;
        }
    }
}
